apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
spec:
  params:
    - name: IMAGE
      type: string
  steps:
    - name: build
      image: docker:latest
      script: |
        #!/bin/sh
        docker build -t $(params.IMAGE) .
