apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-api
  labels:
    app: visits-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-api
  template:
    metadata:
      labels:
        app: visits-api
    spec:
      containers:
        - name: visits-api
          image: crygt/visits-api:latest  # Imagen de Docker Hub
          imagePullPolicy: Always  
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: visits-api-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: visits-api-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: visits-api-config
                  key: DB_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: visits-api-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: visits-api-secret
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
