apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
  namespace: default
spec:
  serviceAccountName: tekton-pipeline-sa
  pipelineRef:
    name: build-and-deploy-api
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc
