apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-api
spec:
  tasks:
    - name: build-image
      taskRef:
        name: build-docker-image
      params:
        - name: IMAGE
          value: "crygt/visits-api:latest"

    - name: deploy-api
      taskRef:
        name: kubectl-deploy
      params:
        - name: KUBERNETES_CLUSTER
          value: "minikube"
        - name: DEPLOYMENT_FILE
          value: "visits-api-deployment.yaml"